### ISSUE TITLE
Allow openfoodnetwork user to manage katuma_reports_unicorn.service

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/katuma-provisioning#10]
Now `openfoodnetwork` can manage the `unicorn_openfoodnetwork.service` but not `katuma_reports_unicorn.service`. This will saves us from having to log with `ofn-admin` just to do that.

**Comment by enricostano** [comment]
https://github.com/coopdevs/katuma-provisioning/pull/8

**Comment by sauloperez** [comment]
katuma_reports_unicorn.service is gone in https://github.com/coopdevs/katuma-provisioning/pull/17.
