### ISSUE TITLE
Add RAILS_ENV to staging

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/katuma-provisioning#6]
As it is not defined if you forget to provide `RAILS_ENV=staging` along the command you run, rails fails to connect to the database.

It should be set up by default.

**Comment by sauloperez** [comment]
Should we use https://github.com/rbenv/rbenv-vars @enricostano ?

We already have it though.

```shell
openfoodnetwork@katuma-staging:~/apps/katuma_reports/current$ rbenv vars
# /home/openfoodnetwork/.rbenv/vars
export GEM_PATH=''$GEM_PATH':'$HOME'/.gems'
```

**Comment by sauloperez** [comment]
Damn it, that is per project and we need something per environment...

**Comment by enricostano** [comment]
we just need to add it at provisioning stage.

**Comment by enricostano** [comment]
This should be done in `ofn-install`, give a look at https://github.com/openfoodfoundation/ofn-install/issues/85

**Comment by sauloperez** [comment]
No need for this issue then.
